#!/bin/bash

echo "🔧 Gmail Email Setup Helper"
echo "=========================="
echo ""
echo "To fix the email sending issue, you need to:"
echo ""
echo "1. 📧 Go to: https://myaccount.google.com/"
echo "2. 🔒 Security → 2-Step Verification (enable if not already)"
echo "3. 🔑 App passwords → Generate password"
echo "4. 📱 Select 'Mail' and generate password"
echo "5. 📋 Copy the 16-character password"
echo ""
echo "Then run this command to update your .env file:"
echo ""
echo "cd /home/girish/Desktop/portfolio/server"
echo "nano .env"
echo ""
echo "Replace 'your-app-password-here' with your actual app password"
echo ""
echo "After updating, restart the server:"
echo "pkill -f 'node server.js' && cd /home/girish/Desktop/portfolio/server && npm run dev"
echo ""
echo "Then test your contact form again!"
